/*global G */
G.audio = {
    JUMP: {
    "osc1_oct": 7,
    "osc1_det": 0,
    "osc1_detune": 0,
    "osc1_xenv": 1,
    "osc1_vol": 255,
    "osc1_waveform": 2,
    "osc2_oct": 8,
    "osc2_det": 0,
    "osc2_detune": 0,
    "osc2_xenv": 1,
    "osc2_vol": 255,
    "osc2_waveform": 2,
    "noise_fader": 0,
    "env_attack": 3706,
    "env_sustain": 0,
    "env_release": 0,
    "env_master": 191,
    "fx_filter": 3,
    "fx_freq": 4067,
    "fx_resonance": 176,
    "fx_delay_time": 4,
    "fx_delay_amt": 44,
    "fx_pan_freq": 2,
    "fx_pan_amt": 84,
    "lfo_osc1_freq": 0,
    "lfo_fx_freq": 1,
    "lfo_freq": 2,
    "lfo_amt": 96,
    "lfo_waveform": 0
    },
    
    FLIP: {
    "osc1_oct": 7,
    "osc1_det": 0,
    "osc1_detune": 0,
    "osc1_xenv": 1,
    "osc1_vol": 255,
    "osc1_waveform": 3,
    "osc2_oct": 5,
    "osc2_det": 0,
    "osc2_detune": 0,
    "osc2_xenv": 1,
    "osc2_vol": 143,
    "osc2_waveform": 3,
    "noise_fader": 255,
    "env_attack": 0,
    "env_sustain": 2418,
    "env_release": 17193,
    "env_master": 57,
    "fx_filter": 1,
    "fx_freq": 4067,
    "fx_resonance": 176,
    "fx_delay_time": 4,
    "fx_delay_amt": 44,
    "fx_pan_freq": 12,
    "fx_pan_amt": 84,
    "lfo_osc1_freq": 0,
    "lfo_fx_freq": 1,
    "lfo_freq": 2,
    "lfo_amt": 160,
    "lfo_waveform": 2
},

    JET: {
    "osc1_oct": 8,
    "osc1_det": 0,
    "osc1_detune": 0,
    "osc1_xenv": 1,
    "osc1_vol": 82,
    "osc1_waveform": 2,
    "osc2_oct": 8,
    "osc2_det": 0,
    "osc2_detune": 0,
    "osc2_xenv": 0,
    "osc2_vol": 0,
    "osc2_waveform": 0,
    "noise_fader": 255,
    "env_attack": 100,
    "env_sustain": 23881,
    "env_release": 0,
    "env_master": 232,
    "fx_filter": 3,
    "fx_freq": 392,
    "fx_resonance": 47,
    "fx_delay_time": 0,
    "fx_delay_amt": 0,
    "fx_pan_freq": 0,
    "fx_pan_amt": 0,
    "lfo_osc1_freq": 0,
    "lfo_fx_freq": 0,
    "lfo_freq": 0,
    "lfo_amt": 0,
    "lfo_waveform": 0
},

    GAMESONG: {
    "songLen": 154,
    "songData": [
        {
            "osc1_oct": 9,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 255,
            "osc1_waveform": 3,
            "osc2_oct": 9,
            "osc2_det": 0,
            "osc2_detune": 14,
            "osc2_xenv": 0,
            "osc2_vol": 255,
            "osc2_waveform": 3,
            "noise_fader": 0,
            "env_attack": 100000,
            "env_sustain": 28181,
            "env_release": 100000,
            "env_master": 106,
            "fx_filter": 3,
            "fx_freq": 3700,
            "fx_resonance": 88,
            "fx_delay_time": 8,
            "fx_delay_amt": 121,
            "fx_pan_freq": 1,
            "fx_pan_amt": 22,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 4,
            "lfo_amt": 228,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                1,
                2,
                1,
                2,
                1,
                2,
                1,
                2,
                0,
                0,
                1,
                2,
                1,
                2
            ],
            "c": [
                {
                    "n": [
                        123,
                        138,
                        135,
                        150,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        119,
                        138,
                        131,
                        150,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        119,
                        140,
                        143,
                        152,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        116,
                        138,
                        140,
                        150,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 7,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 255,
            "osc1_waveform": 2,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 18,
            "osc2_xenv": 0,
            "osc2_vol": 255,
            "osc2_waveform": 2,
            "noise_fader": 0,
            "env_attack": 100000,
            "env_sustain": 56363,
            "env_release": 100000,
            "env_master": 199,
            "fx_filter": 2,
            "fx_freq": 200,
            "fx_resonance": 254,
            "fx_delay_time": 8,
            "fx_delay_amt": 24,
            "fx_pan_freq": 0,
            "fx_pan_amt": 0,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 0,
            "lfo_freq": 0,
            "lfo_amt": 0,
            "lfo_waveform": 0,
            "p": [
                3,
                4,
                3,
                4,
                3,
                4,
                3,
                4,
                3,
                4,
                5,
                6,
                3,
                4,
                3,
                4,
                3,
                5
            ],
            "c": [
                {
                    "n": [
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        123,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        119,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        121,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        116,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        111,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        111,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        111,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 8,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 0,
            "osc1_waveform": 0,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 0,
            "osc2_vol": 0,
            "osc2_waveform": 0,
            "noise_fader": 255,
            "env_attack": 100000,
            "env_sustain": 100000,
            "env_release": 100000,
            "env_master": 192,
            "fx_filter": 2,
            "fx_freq": 2500,
            "fx_resonance": 16,
            "fx_delay_time": 3,
            "fx_delay_amt": 157,
            "fx_pan_freq": 0,
            "fx_pan_amt": 0,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 3,
            "lfo_amt": 51,
            "lfo_waveform": 0,
            "p": [
                1,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1
            ],
            "c": [
                {
                    "n": [
                        135,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        135,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 8,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 1,
            "osc1_vol": 255,
            "osc1_waveform": 0,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 0,
            "osc2_vol": 0,
            "osc2_waveform": 0,
            "noise_fader": 0,
            "env_attack": 0,
            "env_sustain": 0,
            "env_release": 6363,
            "env_master": 239,
            "fx_filter": 0,
            "fx_freq": 7400,
            "fx_resonance": 126,
            "fx_delay_time": 0,
            "fx_delay_amt": 0,
            "fx_pan_freq": 0,
            "fx_pan_amt": 0,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 0,
            "lfo_freq": 0,
            "lfo_amt": 0,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                1,
                1,
                1,
                1
            ],
            "c": [
                {
                    "n": [
                        135,
                        135,
                        0,
                        0,
                        0,
                        0,
                        135,
                        0,
                        135,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        135,
                        135,
                        0,
                        0,
                        0,
                        0,
                        135,
                        0,
                        135,
                        0,
                        0,
                        135,
                        0,
                        0,
                        135,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 8,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 1,
            "osc1_vol": 255,
            "osc1_waveform": 0,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 0,
            "osc2_vol": 0,
            "osc2_waveform": 0,
            "noise_fader": 112,
            "env_attack": 1818,
            "env_sustain": 0,
            "env_release": 18181,
            "env_master": 254,
            "fx_filter": 3,
            "fx_freq": 6600,
            "fx_resonance": 78,
            "fx_delay_time": 3,
            "fx_delay_amt": 73,
            "fx_pan_freq": 0,
            "fx_pan_amt": 0,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 4,
            "lfo_amt": 85,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                0,
                1,
                1,
                1,
                1
            ],
            "c": [
                {
                    "n": [
                        0,
                        0,
                        0,
                        0,
                        135,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        135,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        135,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        135,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 9,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 255,
            "osc1_waveform": 0,
            "osc2_oct": 9,
            "osc2_det": 0,
            "osc2_detune": 12,
            "osc2_xenv": 0,
            "osc2_vol": 255,
            "osc2_waveform": 0,
            "noise_fader": 0,
            "env_attack": 100,
            "env_sustain": 0,
            "env_release": 14545,
            "env_master": 70,
            "fx_filter": 0,
            "fx_freq": 0,
            "fx_resonance": 240,
            "fx_delay_time": 2,
            "fx_delay_amt": 157,
            "fx_pan_freq": 0,
            "fx_pan_amt": 0,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 0,
            "lfo_freq": 0,
            "lfo_amt": 0,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                2,
                1,
                2,
                0,
                0,
                0,
                0,
                1,
                2
            ],
            "c": [
                {
                    "n": [
                        135,
                        147,
                        135,
                        147,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        145,
                        0,
                        147,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        138,
                        150,
                        138,
                        0,
                        137,
                        149,
                        137,
                        0
                    ]
                },
                {
                    "n": [
                        128,
                        140,
                        143,
                        142,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        133,
                        145,
                        133,
                        0,
                        140,
                        152,
                        155,
                        154,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 9,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 255,
            "osc1_waveform": 2,
            "osc2_oct": 10,
            "osc2_det": 0,
            "osc2_detune": 28,
            "osc2_xenv": 0,
            "osc2_vol": 255,
            "osc2_waveform": 2,
            "noise_fader": 0,
            "env_attack": 100,
            "env_sustain": 0,
            "env_release": 5454,
            "env_master": 254,
            "fx_filter": 2,
            "fx_freq": 7800,
            "fx_resonance": 94,
            "fx_delay_time": 3,
            "fx_delay_amt": 103,
            "fx_pan_freq": 0,
            "fx_pan_amt": 0,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 7,
            "lfo_amt": 128,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                2,
                1,
                2,
                1,
                2,
                1,
                2
            ],
            "c": [
                {
                    "n": [
                        0,
                        135,
                        137,
                        0,
                        137,
                        138,
                        0,
                        138,
                        140,
                        0,
                        140,
                        142,
                        0,
                        142,
                        143,
                        145,
                        0,
                        135,
                        137,
                        0,
                        137,
                        138,
                        0,
                        138,
                        140,
                        0,
                        140,
                        142,
                        0,
                        142,
                        143,
                        145
                    ]
                },
                {
                    "n": [
                        0,
                        135,
                        137,
                        0,
                        137,
                        138,
                        0,
                        138,
                        140,
                        0,
                        140,
                        142,
                        0,
                        142,
                        143,
                        145,
                        0,
                        135,
                        137,
                        0,
                        137,
                        138,
                        0,
                        138,
                        140,
                        0,
                        140,
                        142,
                        150,
                        149,
                        147,
                        149
                    ]
                }
            ]
        },
        {
            "osc1_oct": 8,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 1,
            "osc1_vol": 82,
            "osc1_waveform": 2,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 0,
            "osc2_vol": 0,
            "osc2_waveform": 0,
            "noise_fader": 255,
            "env_attack": 100,
            "env_sustain": 0,
            "env_release": 9090,
            "env_master": 232,
            "fx_filter": 3,
            "fx_freq": 5200,
            "fx_resonance": 63,
            "fx_delay_time": 0,
            "fx_delay_amt": 0,
            "fx_pan_freq": 0,
            "fx_pan_amt": 0,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 0,
            "lfo_freq": 0,
            "lfo_amt": 0,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                2,
                2
            ],
            "c": [
                {
                    "n": [
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        0,
                        0,
                        135,
                        0,
                        0,
                        0,
                        135,
                        0,
                        0,
                        0,
                        135,
                        0,
                        0,
                        135,
                        135,
                        0,
                        0,
                        0,
                        135,
                        0,
                        0,
                        0,
                        135,
                        0,
                        0,
                        0,
                        135,
                        135,
                        0,
                        0,
                        135,
                        0
                    ]
                }
            ]
        }
    ],
    "rowLen": 11025,
    "endPattern": 19
}

};

//thoughts: look into how to 'muffle' sound with a audio node. Can alter music playback depending on map space